- name: setup nginx single-page site on ubuntu
  hosts: webservers

  tasks:
    - name: update APT cache
      apt:
        update_cache: yes
    
    - name: install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: start nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: upload index file
      copy:
        src: ./index.html
        dest: /var/www/html/index.html
        force: yes