- name: Setup Nginx single-page site on Ubuntu
  hosts: webservers

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes
    
    - name: Ensure Nginx is installed 
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx service is enabled
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Upload index file
      copy:
        src: ./index.html
        dest: /var/www/html/index.html
        force: yes